package com.merrichat.net.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.merrichat.net.model.DraftDaoModel;
import com.merrichat.net.model.ExpressNotificationModel;
import com.merrichat.net.model.GroupMessage;
import com.merrichat.net.model.MessageListModle;
import com.merrichat.net.model.MessageModel;
import com.merrichat.net.model.NoticeModel;
import com.merrichat.net.model.UserModel;

import com.merrichat.net.model.dao.DraftDaoModelDao;
import com.merrichat.net.model.dao.ExpressNotificationModelDao;
import com.merrichat.net.model.dao.GroupMessageDao;
import com.merrichat.net.model.dao.MessageListModleDao;
import com.merrichat.net.model.dao.MessageModelDao;
import com.merrichat.net.model.dao.NoticeModelDao;
import com.merrichat.net.model.dao.UserModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig draftDaoModelDaoConfig;
    private final DaoConfig expressNotificationModelDaoConfig;
    private final DaoConfig groupMessageDaoConfig;
    private final DaoConfig messageListModleDaoConfig;
    private final DaoConfig messageModelDaoConfig;
    private final DaoConfig noticeModelDaoConfig;
    private final DaoConfig userModelDaoConfig;

    private final DraftDaoModelDao draftDaoModelDao;
    private final ExpressNotificationModelDao expressNotificationModelDao;
    private final GroupMessageDao groupMessageDao;
    private final MessageListModleDao messageListModleDao;
    private final MessageModelDao messageModelDao;
    private final NoticeModelDao noticeModelDao;
    private final UserModelDao userModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        draftDaoModelDaoConfig = daoConfigMap.get(DraftDaoModelDao.class).clone();
        draftDaoModelDaoConfig.initIdentityScope(type);

        expressNotificationModelDaoConfig = daoConfigMap.get(ExpressNotificationModelDao.class).clone();
        expressNotificationModelDaoConfig.initIdentityScope(type);

        groupMessageDaoConfig = daoConfigMap.get(GroupMessageDao.class).clone();
        groupMessageDaoConfig.initIdentityScope(type);

        messageListModleDaoConfig = daoConfigMap.get(MessageListModleDao.class).clone();
        messageListModleDaoConfig.initIdentityScope(type);

        messageModelDaoConfig = daoConfigMap.get(MessageModelDao.class).clone();
        messageModelDaoConfig.initIdentityScope(type);

        noticeModelDaoConfig = daoConfigMap.get(NoticeModelDao.class).clone();
        noticeModelDaoConfig.initIdentityScope(type);

        userModelDaoConfig = daoConfigMap.get(UserModelDao.class).clone();
        userModelDaoConfig.initIdentityScope(type);

        draftDaoModelDao = new DraftDaoModelDao(draftDaoModelDaoConfig, this);
        expressNotificationModelDao = new ExpressNotificationModelDao(expressNotificationModelDaoConfig, this);
        groupMessageDao = new GroupMessageDao(groupMessageDaoConfig, this);
        messageListModleDao = new MessageListModleDao(messageListModleDaoConfig, this);
        messageModelDao = new MessageModelDao(messageModelDaoConfig, this);
        noticeModelDao = new NoticeModelDao(noticeModelDaoConfig, this);
        userModelDao = new UserModelDao(userModelDaoConfig, this);

        registerDao(DraftDaoModel.class, draftDaoModelDao);
        registerDao(ExpressNotificationModel.class, expressNotificationModelDao);
        registerDao(GroupMessage.class, groupMessageDao);
        registerDao(MessageListModle.class, messageListModleDao);
        registerDao(MessageModel.class, messageModelDao);
        registerDao(NoticeModel.class, noticeModelDao);
        registerDao(UserModel.class, userModelDao);
    }
    
    public void clear() {
        draftDaoModelDaoConfig.clearIdentityScope();
        expressNotificationModelDaoConfig.clearIdentityScope();
        groupMessageDaoConfig.clearIdentityScope();
        messageListModleDaoConfig.clearIdentityScope();
        messageModelDaoConfig.clearIdentityScope();
        noticeModelDaoConfig.clearIdentityScope();
        userModelDaoConfig.clearIdentityScope();
    }

    public DraftDaoModelDao getDraftDaoModelDao() {
        return draftDaoModelDao;
    }

    public ExpressNotificationModelDao getExpressNotificationModelDao() {
        return expressNotificationModelDao;
    }

    public GroupMessageDao getGroupMessageDao() {
        return groupMessageDao;
    }

    public MessageListModleDao getMessageListModleDao() {
        return messageListModleDao;
    }

    public MessageModelDao getMessageModelDao() {
        return messageModelDao;
    }

    public NoticeModelDao getNoticeModelDao() {
        return noticeModelDao;
    }

    public UserModelDao getUserModelDao() {
        return userModelDao;
    }

}
