package com.merrichat.net.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.merrichat.net.model.GroupMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP_MESSAGE".
*/
public class GroupMessageDao extends AbstractDao<GroupMessage, Long> {

    public static final String TABLENAME = "GROUP_MESSAGE";

    /**
     * Properties of entity GroupMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "_id");
        public final static Property Mid = new Property(1, String.class, "mid", false, "mid");
        public final static Property Type = new Property(2, String.class, "type", false, "type");
        public final static Property Title = new Property(3, String.class, "title", false, "title");
        public final static Property Content = new Property(4, String.class, "content", false, "content");
        public final static Property Sender = new Property(5, String.class, "sender", false, "sender");
        public final static Property SenderName = new Property(6, String.class, "senderName", false, "senderName");
        public final static Property Receiver = new Property(7, String.class, "receiver", false, "receiver");
        public final static Property ReceiverName = new Property(8, String.class, "receiverName", false, "receiverName");
        public final static Property File = new Property(9, String.class, "file", false, "file");
        public final static Property SpeechTimeLength = new Property(10, String.class, "speechTimeLength", false, "speechTimeLength");
        public final static Property FilePath = new Property(11, String.class, "filePath", false, "filePath");
        public final static Property FileType = new Property(12, String.class, "fileType", false, "fileType");
        public final static Property Format = new Property(13, String.class, "format", false, "format");
        public final static Property Timestamp = new Property(14, long.class, "timestamp", false, "timestamp");
        public final static Property GroupId = new Property(15, String.class, "groupId", false, "groupId");
        public final static Property Group = new Property(16, String.class, "group", false, "group");
        public final static Property Header = new Property(17, String.class, "header", false, "header");
        public final static Property Logo = new Property(18, String.class, "logo", false, "logo");
        public final static Property SendState = new Property(19, int.class, "sendState", false, "sendState");
        public final static Property Thumb = new Property(20, String.class, "thumb", false, "thumb");
        public final static Property ShowTimeState = new Property(21, int.class, "showTimeState", false, "showTimeState");
        public final static Property IsReadVoice = new Property(22, boolean.class, "isReadVoice", false, "is_read_voice");
        public final static Property Inter = new Property(23, String.class, "inter", false, "inter");
        public final static Property Top = new Property(24, String.class, "top", false, "top");
        public final static Property Topts = new Property(25, String.class, "topts", false, "topts");
        public final static Property Private_id = new Property(26, String.class, "private_id", false, "private_id");
        public final static Property RedTid = new Property(27, String.class, "redTid", false, "redTid");
        public final static Property RedStatus = new Property(28, String.class, "redStatus", false, "redStatus");
    }


    public GroupMessageDao(DaoConfig config) {
        super(config);
    }
    
    public GroupMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP_MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"mid\" TEXT," + // 1: mid
                "\"type\" TEXT," + // 2: type
                "\"title\" TEXT," + // 3: title
                "\"content\" TEXT," + // 4: content
                "\"sender\" TEXT," + // 5: sender
                "\"senderName\" TEXT," + // 6: senderName
                "\"receiver\" TEXT," + // 7: receiver
                "\"receiverName\" TEXT," + // 8: receiverName
                "\"file\" TEXT," + // 9: file
                "\"speechTimeLength\" TEXT," + // 10: speechTimeLength
                "\"filePath\" TEXT," + // 11: filePath
                "\"fileType\" TEXT," + // 12: fileType
                "\"format\" TEXT," + // 13: format
                "\"timestamp\" INTEGER NOT NULL ," + // 14: timestamp
                "\"groupId\" TEXT," + // 15: groupId
                "\"group\" TEXT," + // 16: group
                "\"header\" TEXT," + // 17: header
                "\"logo\" TEXT," + // 18: logo
                "\"sendState\" INTEGER NOT NULL ," + // 19: sendState
                "\"thumb\" TEXT," + // 20: thumb
                "\"showTimeState\" INTEGER NOT NULL ," + // 21: showTimeState
                "\"is_read_voice\" INTEGER NOT NULL ," + // 22: isReadVoice
                "\"inter\" TEXT," + // 23: inter
                "\"top\" TEXT," + // 24: top
                "\"topts\" TEXT," + // 25: topts
                "\"private_id\" TEXT," + // 26: private_id
                "\"redTid\" TEXT," + // 27: redTid
                "\"redStatus\" TEXT);"); // 28: redStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP_MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GroupMessage entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String mid = entity.getMid();
        if (mid != null) {
            stmt.bindString(2, mid);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
 
        String sender = entity.getSender();
        if (sender != null) {
            stmt.bindString(6, sender);
        }
 
        String senderName = entity.getSenderName();
        if (senderName != null) {
            stmt.bindString(7, senderName);
        }
 
        String receiver = entity.getReceiver();
        if (receiver != null) {
            stmt.bindString(8, receiver);
        }
 
        String receiverName = entity.getReceiverName();
        if (receiverName != null) {
            stmt.bindString(9, receiverName);
        }
 
        String file = entity.getFile();
        if (file != null) {
            stmt.bindString(10, file);
        }
 
        String speechTimeLength = entity.getSpeechTimeLength();
        if (speechTimeLength != null) {
            stmt.bindString(11, speechTimeLength);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(12, filePath);
        }
 
        String fileType = entity.getFileType();
        if (fileType != null) {
            stmt.bindString(13, fileType);
        }
 
        String format = entity.getFormat();
        if (format != null) {
            stmt.bindString(14, format);
        }
        stmt.bindLong(15, entity.getTimestamp());
 
        String groupId = entity.getGroupId();
        if (groupId != null) {
            stmt.bindString(16, groupId);
        }
 
        String group = entity.getGroup();
        if (group != null) {
            stmt.bindString(17, group);
        }
 
        String header = entity.getHeader();
        if (header != null) {
            stmt.bindString(18, header);
        }
 
        String logo = entity.getLogo();
        if (logo != null) {
            stmt.bindString(19, logo);
        }
        stmt.bindLong(20, entity.getSendState());
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(21, thumb);
        }
        stmt.bindLong(22, entity.getShowTimeState());
        stmt.bindLong(23, entity.getIsReadVoice() ? 1L: 0L);
 
        String inter = entity.getInter();
        if (inter != null) {
            stmt.bindString(24, inter);
        }
 
        String top = entity.getTop();
        if (top != null) {
            stmt.bindString(25, top);
        }
 
        String topts = entity.getTopts();
        if (topts != null) {
            stmt.bindString(26, topts);
        }
 
        String private_id = entity.getPrivate_id();
        if (private_id != null) {
            stmt.bindString(27, private_id);
        }
 
        String redTid = entity.getRedTid();
        if (redTid != null) {
            stmt.bindString(28, redTid);
        }
 
        String redStatus = entity.getRedStatus();
        if (redStatus != null) {
            stmt.bindString(29, redStatus);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GroupMessage entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String mid = entity.getMid();
        if (mid != null) {
            stmt.bindString(2, mid);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
 
        String sender = entity.getSender();
        if (sender != null) {
            stmt.bindString(6, sender);
        }
 
        String senderName = entity.getSenderName();
        if (senderName != null) {
            stmt.bindString(7, senderName);
        }
 
        String receiver = entity.getReceiver();
        if (receiver != null) {
            stmt.bindString(8, receiver);
        }
 
        String receiverName = entity.getReceiverName();
        if (receiverName != null) {
            stmt.bindString(9, receiverName);
        }
 
        String file = entity.getFile();
        if (file != null) {
            stmt.bindString(10, file);
        }
 
        String speechTimeLength = entity.getSpeechTimeLength();
        if (speechTimeLength != null) {
            stmt.bindString(11, speechTimeLength);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(12, filePath);
        }
 
        String fileType = entity.getFileType();
        if (fileType != null) {
            stmt.bindString(13, fileType);
        }
 
        String format = entity.getFormat();
        if (format != null) {
            stmt.bindString(14, format);
        }
        stmt.bindLong(15, entity.getTimestamp());
 
        String groupId = entity.getGroupId();
        if (groupId != null) {
            stmt.bindString(16, groupId);
        }
 
        String group = entity.getGroup();
        if (group != null) {
            stmt.bindString(17, group);
        }
 
        String header = entity.getHeader();
        if (header != null) {
            stmt.bindString(18, header);
        }
 
        String logo = entity.getLogo();
        if (logo != null) {
            stmt.bindString(19, logo);
        }
        stmt.bindLong(20, entity.getSendState());
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(21, thumb);
        }
        stmt.bindLong(22, entity.getShowTimeState());
        stmt.bindLong(23, entity.getIsReadVoice() ? 1L: 0L);
 
        String inter = entity.getInter();
        if (inter != null) {
            stmt.bindString(24, inter);
        }
 
        String top = entity.getTop();
        if (top != null) {
            stmt.bindString(25, top);
        }
 
        String topts = entity.getTopts();
        if (topts != null) {
            stmt.bindString(26, topts);
        }
 
        String private_id = entity.getPrivate_id();
        if (private_id != null) {
            stmt.bindString(27, private_id);
        }
 
        String redTid = entity.getRedTid();
        if (redTid != null) {
            stmt.bindString(28, redTid);
        }
 
        String redStatus = entity.getRedStatus();
        if (redStatus != null) {
            stmt.bindString(29, redStatus);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GroupMessage readEntity(Cursor cursor, int offset) {
        GroupMessage entity = new GroupMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // content
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // sender
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // senderName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // receiver
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // receiverName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // file
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // speechTimeLength
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // filePath
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // fileType
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // format
            cursor.getLong(offset + 14), // timestamp
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // groupId
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // group
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // header
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // logo
            cursor.getInt(offset + 19), // sendState
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // thumb
            cursor.getInt(offset + 21), // showTimeState
            cursor.getShort(offset + 22) != 0, // isReadVoice
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // inter
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // top
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // topts
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // private_id
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // redTid
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28) // redStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GroupMessage entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSender(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSenderName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setReceiver(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setReceiverName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFile(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSpeechTimeLength(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFilePath(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setFileType(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setFormat(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setTimestamp(cursor.getLong(offset + 14));
        entity.setGroupId(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setGroup(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setHeader(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setLogo(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setSendState(cursor.getInt(offset + 19));
        entity.setThumb(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setShowTimeState(cursor.getInt(offset + 21));
        entity.setIsReadVoice(cursor.getShort(offset + 22) != 0);
        entity.setInter(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setTop(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setTopts(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setPrivate_id(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setRedTid(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setRedStatus(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GroupMessage entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GroupMessage entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GroupMessage entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
